Feature/nav 150 extract python viewer package
naviqore/public-transit-viewer pull request #14
Opened 2024-08-21 23:13 UTC by munterfi

2024-08-26 15:55 UTC, munterfi commented
@clukas1, I think we could merge this and release the viewer with version 0.5.0?

2024-08-26 19:21 UTC, clukas1 requested changes
@munterfi nice work. No real comments on your work. Just noticed a bug that marker points were not showing correctly depending on time_type. So think this could easily be fixed in this commit before we release 0.5.0

2024-08-26 19:21 UTC, clukas1 commented on public_transit_viewer/pages/isolines.py
> +            location=source_coordinates,  # type: ignore
needs more logic:
`location=target_coordinates if time_type == TimeType.DEPARTURE else source_coordinates`

2024-08-26 19:21 UTC, clukas1 commented on public_transit_viewer/pages/isolines.py
> +            popup = f"{data_row['targetStop']} - {data_row['durationFromSourceInMinutes']} min"
same here, targetStop if timeType == DEPARTURE else sourceStop

2024-08-26 19:21 UTC, clukas1 commented on public_transit_viewer/pages/isolines.py
> +        location=[data_row["targetLat"], data_row["targetLon"]],  # type: ignore
also time type specific:
DEPARTURE == target else source

2024-08-26 19:21 UTC, clukas1 commented on public_transit_viewer/pages/isolines.py
> +        popup=f"{data_row['targetStop']} - {arrival_time} minutes",  # type: ignore
same logic issue

2024-08-27 11:34 UTC, munterfi commented on public_transit_viewer/pages/isolines.py
> +        popup=f"{data_row['targetStop']} - {arrival_time} minutes",  # type: ignore
[b79fe3e](https://github.com/naviqore/public-transit-viewer/pull/14/commits/b79fe3ef86cc2de0103e8127595317a1e5d8b362)

2024-08-27 11:34 UTC, munterfi commented on public_transit_viewer/pages/isolines.py
> +        location=[data_row["targetLat"], data_row["targetLon"]],  # type: ignore
[b79fe3e](https://github.com/naviqore/public-transit-viewer/pull/14/commits/b79fe3ef86cc2de0103e8127595317a1e5d8b362)

2024-08-27 11:34 UTC, munterfi commented on public_transit_viewer/pages/isolines.py
> +            location=source_coordinates,  # type: ignore
[b79fe3e](https://github.com/naviqore/public-transit-viewer/pull/14/commits/b79fe3ef86cc2de0103e8127595317a1e5d8b362)

2024-08-27 11:34 UTC, munterfi commented on public_transit_viewer/pages/isolines.py
> +            popup = f"{data_row['targetStop']} - {data_row['durationFromSourceInMinutes']} min"
[b79fe3e](https://github.com/naviqore/public-transit-viewer/pull/14/commits/b79fe3ef86cc2de0103e8127595317a1e5d8b362)

2024-08-28 21:15 UTC, clukas1 approved these changes

2024-08-28 21:16 UTC, merged